# [START app_yaml]
runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: flask
  version: "0.12"

# [END app_yaml]